### ISSUE TITLE
Wierd IP address when I curl

### ISSUE THREAD

**Issue by njmurarka** [catflip/bluzelle-discord#1]
curl icanhazip.com
2001:569:74e0:6700:5d81:583c:9b3d:8d9a

**Comment by spiritbro1** [comment]
sorry what vps you use?

**Comment by njmurarka** [comment]
I am running locally only so far... not VPS. Local MacOS.

**Comment by spiritbro1** [comment]
sorry @njmurarka  i didn't mention in the youtube video that i use vps and linux on there so im not tested it in macOS so i think it's very different basically what that command does is just to get the external ip address which then can be used to open frontend like this http://bluzelle-discord.rino.world/ it should be on vps only actually if you use it on local no need to do that sorry i will change readme.MD
