### ISSUE TITLE
I followed the instructions. Bot came up on CLI, but no response in Discord

### ISSUE THREAD

**Issue by njmurarka** [catflip/bluzelle-discord#3]
I tried !deploy

I tried /help

No reply...

**Comment by njmurarka** [comment]
<img width="493" alt="Screen Shot 2021-07-20 at 18 51 59" src="https://user-images.githubusercontent.com/471362/126418089-71eff95c-88fa-4f16-b02f-22a2d5aa2117.png">

**Comment by spiritbro1** [comment]
@njmurarka is it say ready in command line? have you change the .env variable ? how do you run it using local development? or vps?

**Comment by spiritbro1** [comment]
i forgot for the slash command to show should wait proximately 1 minute but sometimes less than that

**Comment by njmurarka** [comment]
npx ts-node-dev src/index.ts
npx: installed 52 in 2.671s
[INFO] 19:00:04 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 3.8.3)
Ready!

(yes, it says ready)

**Comment by njmurarka** [comment]
I waited longer than one minute...

**Comment by spiritbro1** [comment]
have you change the .env file?

**Comment by spiritbro1** [comment]
https://github.com/spiritbro1/bluzelle-discord#tutorial-to-setup-local-development you should follow this instruction for local development

**Comment by njmurarka** [comment]
I already followed the local development instructions... and I did create the .env file already:

more .env
DISCORD_TOKEN=<...>
DISCORD_INVITE=<...>
WEBSITE=

**Comment by spiritbro1** [comment]
try to run !deploy again until message `command has been deployed` shown

**Comment by njmurarka** [comment]
I have tried about 8 times. Nothing.

**Comment by spiritbro1** [comment]
![image](https://user-images.githubusercontent.com/62529025/126420144-41d17634-2853-475a-83a0-61253970328e.png)

sorry for the trouble, try to message the bot in the channel like this

**Comment by njmurarka** [comment]
This is exactly what I did. It does not say "command has been deployed"
immediately, or ever...

**Comment by njmurarka** [comment]
No luck. I deployed on Ubuntu as well. The bot server starts. But !deploy does nothing. Neither does / commands.

I tried this on two different discord servers. 

Please comment on this ASAP. I have had luck deploy other bots on these servers. 

We need to review and close this bounty soon. I await your reply.

**Comment by spiritbro1** [comment]
how about using docker-compose in ubuntu?
